### ISSUE TITLE
Getting a single processor to generate multiple messages onto the next queue

### ISSUE THREAD

**Issue by jamesnyika** [zalky/cues#9]
Hi
 This is a question rather than an issue : How would I (within a single processor - eg. JDBC Database Source processor) that reads 5 records from the database, process all the five records and dump the results of each record processing as a single new output on the following queue for serial processing ? 

 I hope the question is clear ?   a processor generates/reads 5 records and wants to pass them into the next stage of the graph as single records ...

**Comment by zalky** [comment]
Hi @jamesnyika , yes, this makes sense, and it is a reasonable use case for a data graph. There is actually a kind of Cues processor that is not documented called an _imperative_ processor that allows you to do this.

Instead of returning a declarative output map, an imperative processor provides you with an set of tailers and appenders which you can use to explicitly read and write messages in arbitrary ways.

Consider the following addition to the `cues.build/graphs-spec` example graph:

```clj
(defmethod q/processor ::inc-x
  [_ {msg :input}]
  {:output (update msg :x inc)})

(defmethod q/processor ::store-x
  [{{db :db} :opts} {msg :input}]
  (swap! db assoc (:x msg) (dissoc msg :q/meta)))

(defmethod q/processor ::imperative
  ;; New processor
  [{{t :tail} :tailers
    {a :app}  :appenders} {{records :records} :input}]
  (let [imperative-msg (q/read t)]
    (doseq [r records]
      (q/write a (merge r imperative-msg)))))

(defn graph-spec
  [db]
  {:id         ::example
   :source     ::source
   :errors     ::errors
   :queue-opts {::tx {:queue-meta #{:tx/t}}}
   :processors [{:id ::source}
                {:id  ::inc-x
                 :in  {:input ::source}
                 :out {:output ::tx}}
                {:id        ::imperative    ; New processor
                 :in        {:input ::tx}
                 :tailers   {:tail ::q1}
                 :appenders {:app ::q2}}
                {:id   ::store-x
                 :in   {:input ::tx}
                 :opts {:db db}}]})
```
Any processor that includes a `:tailers` or `:appenders` map in its declaration is considered _imperative_. The `:tailers` and `:appenders` maps work just like `:in` and `:out`, but instead of messages they bind tailers and appenders to queues. Every imperative processor must also always have at least _one_ regular `:in` input binding, which defines when each processor "step" happens. As with all Cues processors, you do not need to declare the type, it is inferred from the declaration. 

In this example we declare a `:tail` tailer on the `::q1` queue and an `:app` appender on the `::q2` queue. Messages bound to `:input` from the `::tx` queue will advance the imperative processor loop.

On each step of the `::imperative` processor we:

1. Pull a sequence of records from the `:records` attribute of our `:input` message
2. Perform a non-blocking read of another message from the `:tail` tailer (this is merged into each record purely for demonstration purposes)
3. _For each record_, write an explicit message using our `:app` appender. This means if we had 5 records, we would write 5 separate message in the same step to the `::q2` queue.

I think step 3 is what you were asking about. Step 2 is not actually relevant to your question, but I wanted to include it to fully document all the features of imperative processors.

### Message Delivery Semantics for Imperative Processors

This needs to be discussed as well. Recall that for pure processors Cues provides _exactly once_ message delivery semantics whereas for impure processors delivery semantics on the `:in` and `:out` messages are _at least once_. You can [use the Cues delivery-hash to implement _exactly once_ semantics](https://github.com/zalky/cues#errors-and-exactly-once-message-delivery-), but the implementation is up to you.

Unfortunately things are more complicated for your imperative appenders and tailers. Because you can read and write to them in completely arbitrary ways, the delivery semantics depend entirely on your implementation. You cannot assume which of the three semantics you'll have (_at most once_, _at least once_, _exactly once_) a priori of your implementation.

I had some ideas on how to provide something a little more "batteries included" and generalizable for imperative tailers and appenders, but the problem is quite complex. This is why I held off documenting imperative processors. 

But as long as you don't have strict message delivery requirements, _or_ you are able to fulfill your requirements yourself in your processor function, imperative processors work great and are really powerful. The features that are currently part of the library will not change, and I've used them myself to implement fairly sophisticated architectures.

Let me know if the above answers your question.

**Comment by jamesnyika** [comment]
Hi @zalky .....just reading through to process this... Looks like it will work... just reading through slowly

**Comment by jamesnyika** [comment]
So.. Clarification question

 My batch of 5 records, in a vector say, will arrive as ```input``` for the imperative processor. I really do not need to do anything more to them other than to take each of them and append them one at a time into ``` :a ```.  My question is, you simply did the record merge with a message from ```:t``` to make the point that if you wanted to do complex processing that involved OTHER messages you could, .. but really what I need is access to the appender so that I can break up my sequence of records ? 

Also, when configuring the imperative processor, must you acquire BOTH the tailers and appenders or can you just acquire the one you need ? 

thanks

**Comment by zalky** [comment]
> you simply did the record merge with a message from :t to make the point that if you wanted to do complex processing that involved OTHER messages you could, .. but really what I need is access to the appender so that I can break up my sequence of records ?

@jamesnyika , yes exactly: the `:tail` tailer and merge was just to fully document all the features that are available, but it is not necessary for your problem. All you need is the appender.

> My batch of 5 records, in a vector say, will arrive as input for the imperative processor.

One more thing to consider: if you are building off the `:util.processors/jdbc-reader` processor from the other issue that you created, #8 , you could also use an appender in `:util.processors/jdbc-reader` to directly write your query result as separate messages, rather than having a second dedicated processor to split the results.

A smaller graph is generally a faster graph, with fewer failure points. But then it also depends on your persistence requirements, so I do not want to be too prescriptive.

**Comment by jamesnyika** [comment]
THis is fantastic and answers my question. Thanks!
